# Generated by Django 2.2.17 on 2021-01-17 03:23

from django.db import migrations, models
import django_extensions.db.fields
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EasyLogging',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('username', models.CharField(max_length=150)),
                ('endpoint', models.TextField()),
                ('method', models.CharField(max_length=25)),
                ('ip_addres', models.CharField(blank=True, max_length=25, null=True)),
                ('request_json', jsonfield.fields.JSONField(blank=True, null=True)),
                ('response_json', jsonfield.fields.JSONField(blank=True, null=True)),
                ('kwargs', jsonfield.fields.JSONField(blank=True, null=True)),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
