# Generated by Django 2.2.6 on 2019-10-30 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='born_register',
            new_name='date_register',
        ),
    ]
