# Generated by Django 2.2.9 on 2020-01-11 07:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orm', '0002_auto_20200111_0520'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presenceitem',
            name='member',
        ),
        migrations.AddField(
            model_name='basemember',
            name='activate',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='presenceitem',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member_presence', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='presencecontainer',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creator_presence', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='presenceitem',
            name='supervisor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervisor_presence', to=settings.AUTH_USER_MODEL),
        ),
    ]
