# Generated by Django 2.2.7 on 2019-12-02 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0002_auto_20191030_1336'),
    ]

    operations = [
        migrations.RenameField(
            model_name='branch',
            old_name='region',
            new_name='regional',
        ),
    ]
