# Generated by Django 2.2.9 on 2020-01-11 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0003_auto_20200111_0721'),
    ]

    operations = [
        migrations.AddField(
            model_name='practicescore',
            name='filled',
            field=models.BooleanField(default=False),
        ),
    ]
