# Generated by Django 2.2.7 on 2019-12-02 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0003_auto_20191202_0704'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='qrcode',
            field=models.ImageField(blank=True, null=True, upload_to='qr_code/%Y/%m/%d'),
        ),
    ]
