# Generated by Django 2.2.8 on 2019-12-09 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0003_auto_20191209_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='basemember',
            name='blood_type',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('AB', 'AB'), ('O', 'O')], max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='basemember',
            name='disease_history',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='basemember',
            name='identity_card_number',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='basemember',
            name='identity_card_photo',
            field=models.ImageField(blank=True, null=True, upload_to='id_card/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='basemember',
            name='public_photo',
            field=models.ImageField(blank=True, null=True, upload_to='public_photo/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='basemember',
            name='religion',
            field=models.CharField(blank=True, default='islam', max_length=45, null=True),
        ),
    ]
