# Generated by Django 2.2.8 on 2019-12-11 05:19

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orm', '0004_auto_20191209_1737'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ClubCommiteMember',
            new_name='ClubUnitCommiteMember',
        ),
        migrations.DeleteModel(
            name='UnitCommiteMember',
        ),
    ]
