# Generated by Django 2.2.7 on 2019-12-03 15:31

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0004_member_qrcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArcheryRange',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField(null=True)),
                ('latitude', models.CharField(max_length=25)),
                ('longitude', models.CharField(max_length=25)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='archery_ranges', to='orm.Club')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='archery_ranges', to='orm.Unit')),
            ],
        ),
        migrations.RemoveField(
            model_name='branch',
            name='regional',
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('regional', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provinces', to='orm.Region')),
            ],
        ),
        migrations.CreateModel(
            name='Precense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('note', models.TextField(null=True)),
                ('archery_range', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archery_range_precenses', to='orm.ArcheryRange')),
                ('member', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member_precenses', to='orm.Member')),
                ('supervisor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervisor_precenses', to='orm.Member')),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='branch',
            name='province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='branchs', to='orm.Province'),
        ),
    ]
