# Generated by Django 2.2.9 on 2020-01-23 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0004_practicescore_filled'),
    ]

    operations = [
        migrations.AddField(
            model_name='practiceseries',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
