# Generated by Django 2.2.8 on 2019-12-16 15:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0007_auto_20191216_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='practice',
            name='completed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='practice',
            name='signed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='practice',
            name='signed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='practices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='practice',
            name='status',
            field=models.CharField(blank=True, choices=[('0', 'Waiting'), ('1', 'Rejected'), ('3', 'Approved')], default='0', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='practiceseries',
            name='closed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
