# Generated by Django 2.2.8 on 2019-12-24 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0008_auto_20191216_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='basemember',
            name='full_name',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
