# Generated by Django 2.2.8 on 2019-12-24 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0010_auto_20191224_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='presencecontainer',
            name='club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='club_presence', to='orm.Club'),
        ),
        migrations.AddField(
            model_name='presencecontainer',
            name='satuan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='satuan_presence', to='orm.Unit'),
        ),
        migrations.AlterField(
            model_name='presencecontainer',
            name='creator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creator_presence', to='orm.BaseMember'),
        ),
    ]
