# Generated by Django 2.2.8 on 2019-12-25 09:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orm', '0011_auto_20191224_1431'),
    ]

    operations = [
        migrations.CreateModel(
            name='PracticeContainer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('target_type', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('distance', models.FloatField(default=1)),
                ('series', models.IntegerField(default=1)),
                ('arrow', models.IntegerField(default=1)),
                ('status', models.CharField(blank=True, choices=[('0', 'Waiting'), ('1', 'Rejected'), ('3', 'Approved')], default='0', max_length=50, null=True)),
                ('signed', models.BooleanField(blank=True, default=False, null=True)),
                ('completed', models.BooleanField(blank=True, default=False, null=True)),
                ('member', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='practices', to='orm.ArcherMember')),
                ('signed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='practices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='practiceseries',
            name='practice',
        ),
        migrations.AddField(
            model_name='practiceseries',
            name='serie',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='presencecontainer',
            name='title',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Practice',
        ),
        migrations.AddField(
            model_name='practiceseries',
            name='practice_container',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='practice_series', to='orm.PracticeContainer'),
            preserve_default=False,
        ),
    ]
