# Generated by Django 2.2.9 on 2020-01-01 04:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0012_auto_20191225_0934'),
    ]

    operations = [
        migrations.AddField(
            model_name='presencecontainer',
            name='latitude',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='presencecontainer',
            name='longitude',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='presenceitem',
            name='member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member_presence', to='orm.BaseMember'),
        ),
    ]
