# Generated by Django 2.2.9 on 2020-01-01 05:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0013_auto_20200101_0458'),
    ]

    operations = [
        migrations.AddField(
            model_name='practicecontainer',
            name='archery_range',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='practices', to='orm.ArcheryRange'),
        ),
        migrations.AddField(
            model_name='practicecontainer',
            name='latitude',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='practicecontainer',
            name='longitude',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='practicecontainer',
            name='member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='practices', to='orm.BaseMember'),
        ),
    ]
