# Generated by Django 2.2.9 on 2020-01-04 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orm', '0014_auto_20200101_0510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archeryrange',
            name='club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archery_ranges', to='orm.Club'),
        ),
        migrations.AlterField(
            model_name='archeryrange',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archery_ranges', to='orm.Unit'),
        ),
    ]
