# Generated by Django 2.2.17 on 2020-12-24 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('region', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kabupaten',
            options={'ordering': ['created']},
        ),
        migrations.AlterModelOptions(
            name='kecamatan',
            options={'ordering': ['created']},
        ),
        migrations.AlterModelOptions(
            name='kelurahan',
            options={'ordering': ['created']},
        ),
        migrations.AlterModelOptions(
            name='provinsi',
            options={'ordering': ['created']},
        ),
        migrations.AlterModelOptions(
            name='regional',
            options={'ordering': ['created']},
        ),
    ]
