# Generated by Django 2.2.10 on 2020-03-26 16:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('club', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PhysicInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body_height', models.CharField(blank=True, default='0', max_length=25, null=True)),
                ('body_weight', models.CharField(blank=True, default='0', max_length=25, null=True)),
                ('draw_length', models.CharField(blank=True, default='0', max_length=25, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChangeRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('username', models.CharField(blank=True, max_length=10, null=True)),
                ('status', models.CharField(blank=True, choices=[('1', 'Menunggu Persetujuan'), ('2', 'Diterima'), ('3', 'Ditolak')], default='1', max_length=10, null=True)),
                ('closed', models.BooleanField(blank=True, default=False, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='change_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BaseMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('full_name', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('phone', models.CharField(max_length=15)),
                ('gender', models.CharField(choices=[('pria', 'Pria'), ('wanita', 'Wanita')], max_length=10)),
                ('born_place', models.CharField(blank=True, max_length=45, null=True)),
                ('born_date', models.DateField(blank=True, null=True)),
                ('address', models.TextField()),
                ('date_register', models.DateField(blank=True, null=True)),
                ('religion', models.CharField(blank=True, default='islam', max_length=45, null=True)),
                ('identity_card_number', models.CharField(blank=True, max_length=45, null=True)),
                ('identity_card_photo', models.ImageField(blank=True, null=True, upload_to='id_card/%Y/%m/%d')),
                ('blood_type', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('AB', 'AB'), ('O', 'O')], max_length=45, null=True)),
                ('disease_history', models.TextField(blank=True, default=None, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photo/%Y/%m/%d')),
                ('public_photo', models.ImageField(blank=True, null=True, upload_to='public_photo/%Y/%m/%d')),
                ('qrcode', models.ImageField(blank=True, null=True, upload_to='qr_code/%Y/%m/%d')),
                ('skck', models.ImageField(blank=True, null=True, upload_to='skck/%Y/%m/%d')),
                ('status', models.CharField(blank=True, choices=[('1', 'Menunggu Persetujuan'), ('2', 'Diterima'), ('3', 'Ditolak')], default='1', max_length=10, null=True)),
                ('closed', models.BooleanField(blank=True, default=False, null=True)),
                ('activate', models.BooleanField(blank=True, default=False, null=True)),
                ('clubunit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='club.ClubUnit')),
                ('physic_information', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='basemember', to='member.PhysicInformation')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='basemember', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ArcherMember',
            fields=[
                ('basemember_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='member.BaseMember')),
                ('verified', models.BooleanField(blank=True, default=False, null=True)),
                ('approved', models.BooleanField(blank=True, default=False, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member_approval', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
            },
            bases=('member.basemember',),
        ),
    ]
