# Generated by Django 2.2.9 on 2020-12-22 14:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('region', '0001_initial'),
        ('club', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Archer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('full_name', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('phone', models.CharField(max_length=15)),
                ('gender', models.CharField(choices=[('pria', 'Pria'), ('wanita', 'Wanita')], max_length=10)),
                ('born_place', models.CharField(blank=True, max_length=45, null=True)),
                ('born_date', models.DateField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('date_register', models.DateField(blank=True, null=True)),
                ('religion', models.CharField(blank=True, choices=[('islam', 'Islam')], default='islam', max_length=45, null=True)),
                ('blood_type', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('AB', 'AB'), ('O', 'O')], max_length=45, null=True)),
                ('disease_history', models.TextField(blank=True, default=None, null=True)),
                ('identity_card_number', models.CharField(blank=True, max_length=45, null=True)),
                ('identity_card_photo', models.ImageField(blank=True, null=True, upload_to='id_card/%Y/%m/%d')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photo/%Y/%m/%d')),
                ('public_photo', models.ImageField(blank=True, null=True, upload_to='public_photo/%Y/%m/%d')),
                ('qrcode', models.ImageField(blank=True, null=True, upload_to='qr_code/%Y/%m/%d')),
                ('skck', models.ImageField(blank=True, null=True, upload_to='skck/%Y/%m/%d')),
                ('body_height', models.CharField(blank=True, default='0', max_length=25, null=True)),
                ('body_weight', models.CharField(blank=True, default='0', max_length=25, null=True)),
                ('draw_length', models.CharField(blank=True, default='0', max_length=25, null=True)),
                ('verified', models.BooleanField(blank=True, default=False, null=True)),
                ('approved', models.BooleanField(blank=True, default=False, null=True)),
                ('region_code_name', models.CharField(blank=True, max_length=100, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archers_approval', to=settings.AUTH_USER_MODEL)),
                ('club', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='club.Club')),
                ('kecamatan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='region.Kecamatan')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
                'abstract': False,
            },
        ),
    ]
