# Generated by Django 2.2.17 on 2020-12-24 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archer', '0002_auto_20201224_0538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archer',
            name='identity_card_number',
            field=models.CharField(blank=True, max_length=45, null=True, unique=True),
        ),
    ]
