# Generated by Django 2.2.17 on 2020-12-26 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archer', '0003_auto_20201224_0728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archer',
            name='gender',
            field=models.CharField(choices=[('Pria', 'Pria'), ('Wanita', 'Wanita')], max_length=10),
        ),
    ]
