# Generated by Django 2.2 on 2020-12-30 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archer', '0004_auto_20201226_0247'),
    ]

    operations = [
        migrations.AddField(
            model_name='archer',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
