# Generated by Django 2.2.17 on 2021-01-13 15:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('archer', '0005_archer_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='archer',
            name='approved',
        ),
        migrations.RemoveField(
            model_name='archer',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='archer',
            name='identity_card_photo',
        ),
        migrations.RemoveField(
            model_name='archer',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='archer',
            name='public_photo',
        ),
        migrations.RemoveField(
            model_name='archer',
            name='skck',
        ),
        migrations.RemoveField(
            model_name='archer',
            name='verified',
        ),
        migrations.AddField(
            model_name='archer',
            name='role',
            field=models.CharField(choices=[('pusat', 'Pengurus Pusat'), ('pengprov', 'Pengurus Provinsi (DPD)'), ('pengcab', 'Pengurus Kabupaten (DPC)'), ('puslat-manager', 'Pengurus Puslat'), ('archer', 'Pemanah')], default='archer', max_length=100),
        ),
        migrations.CreateModel(
            name='ArcherApprovalStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('puslat_approved', models.BooleanField(blank=True, default=False, null=True)),
                ('puslat_approved_on', models.DateTimeField(blank=True, null=True)),
                ('dpc_approved', models.BooleanField(blank=True, default=False, null=True)),
                ('dpc_approved_on', models.DateTimeField(blank=True, null=True)),
                ('dpd_approved', models.BooleanField(blank=True, default=False, null=True)),
                ('dpd_approved_on', models.DateTimeField(blank=True, null=True)),
                ('verified', models.BooleanField(default=False)),
                ('archer', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_status', to='archer.Archer')),
                ('dpc_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dpc_approval', to=settings.AUTH_USER_MODEL)),
                ('dpd_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dpd_approval', to=settings.AUTH_USER_MODEL)),
                ('puslat_approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='puslat_approval', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created', '-modified'],
            },
        ),
        migrations.CreateModel(
            name='ArcherApprovalDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('public_photo', models.ImageField(blank=True, null=True, upload_to='public_photo/%Y/%m/%d')),
                ('photo', models.TextField(blank=True, null=True)),
                ('identity_card_photo', models.ImageField(blank=True, null=True, upload_to='id_card/%Y/%m/%d')),
                ('qrcode', models.ImageField(blank=True, null=True, upload_to='qr_code/%Y/%m/%d')),
                ('skck', models.ImageField(blank=True, null=True, upload_to='skck/%Y/%m/%d')),
                ('archer', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_document', to='archer.Archer')),
            ],
            options={
                'ordering': ['-created', '-modified'],
            },
        ),
    ]
