# Generated by Django 2.2.17 on 2021-01-18 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archer', '0006_auto_20210113_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='archerapprovaldocument',
            name='latsar_photo',
            field=models.ImageField(blank=True, null=True, upload_to='latsar/%Y/%m/%d'),
        ),
    ]
