# Generated by Django 2.2.17 on 2021-01-18 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archer', '0007_archerapprovaldocument_latsar_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='archerapprovaldocument',
            old_name='latsar_photo',
            new_name='latsar_certificate',
        ),
        migrations.RemoveField(
            model_name='archerapprovaldocument',
            name='qrcode',
        ),
    ]
