# Generated by Django 2.2.9 on 2020-05-17 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workoutitem',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
