# Generated by Django 2.2.9 on 2020-05-17 00:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appmenu',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='app_menus', to='menu.MenuCategory'),
        ),
        migrations.AlterField(
            model_name='appmenu',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='menucategory',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
