# Generated by Django 2.2.9 on 2020-05-17 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_auto_20200517_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appmenu',
            name='app_icon',
            field=models.ImageField(blank=True, null=True, upload_to='menu_icon_dir/'),
        ),
    ]
