# Generated by Django 2.2.9 on 2020-05-17 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0002_auto_20200326_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arrow',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bow',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
