# Generated by Django 2.2.17 on 2020-12-24 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='club',
            old_name='kelurahan',
            new_name='village',
        ),
        migrations.AddField(
            model_name='club',
            name='city_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='club',
            name='district_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='club',
            name='province_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
