# Generated by Django 2.2.17 on 2020-12-26 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0002_auto_20201224_0454'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='organisation_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
