# Generated by Django 2.2.17 on 2021-01-09 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0004_auto_20201230_0217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
