# Generated by Django 2.2.17 on 2021-01-16 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0005_auto_20210109_0141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='org_type',
        ),
    ]
