# Generated by Django 2.2.17 on 2021-01-19 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0006_remove_club_org_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='org_type',
            field=models.CharField(choices=[('club', 'Club'), ('satuan', 'Satuan')], default='club', max_length=20),
        ),
    ]
