# Generated by Django 2.2.17 on 2021-01-22 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0007_club_org_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='PracticeSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('practice_day', models.CharField(blank=True, choices=[(0, 'Senin'), (1, 'Selasa'), (2, 'Rabu'), (3, 'Kamis'), (4, 'Jumat'), (5, 'Sabtu'), (6, 'Ahad')], max_length=5, null=True)),
                ('practice_start_time', models.TimeField(blank=True, null=True)),
                ('practice_end_time', models.TimeField(blank=True, null=True)),
                ('archery_range', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='club.ArcheryRange')),
                ('puslat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='club.Club')),
            ],
        ),
    ]
