# Generated by Django 2.2.10 on 2020-03-26 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('region', '0001_initial'),
        ('member', '0001_initial'),
        ('club', '0002_auto_20200326_1627'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommitePosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Periode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_periode', models.CharField(max_length=25)),
                ('end_periode', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='RegionalCommiteMember',
            fields=[
                ('basemember_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='member.BaseMember')),
                ('sk_number', models.CharField(blank=True, max_length=100, null=True)),
                ('sk_document', models.FileField(blank=True, null=True, upload_to='docs/sk/%Y/%m/%d')),
                ('periode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='commite.Periode')),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='commite.CommitePosition')),
                ('regional', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='region.Region')),
            ],
            options={
                'abstract': False,
            },
            bases=('member.basemember',),
        ),
        migrations.CreateModel(
            name='PengprovCommiteMember',
            fields=[
                ('basemember_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='member.BaseMember')),
                ('sk_number', models.CharField(blank=True, max_length=100, null=True)),
                ('sk_document', models.FileField(blank=True, null=True, upload_to='docs/sk/%Y/%m/%d')),
                ('periode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='commite.Periode')),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='commite.CommitePosition')),
                ('province', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='region.Province')),
            ],
            options={
                'abstract': False,
            },
            bases=('member.basemember',),
        ),
        migrations.CreateModel(
            name='PengcabCommiteMember',
            fields=[
                ('basemember_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='member.BaseMember')),
                ('sk_number', models.CharField(blank=True, max_length=100, null=True)),
                ('sk_document', models.FileField(blank=True, null=True, upload_to='docs/sk/%Y/%m/%d')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='club.Branch')),
                ('periode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='commite.Periode')),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='commite.CommitePosition')),
            ],
            options={
                'abstract': False,
            },
            bases=('member.basemember',),
        ),
        migrations.CreateModel(
            name='ClubUnitCommiteMember',
            fields=[
                ('basemember_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='member.BaseMember')),
                ('sk_number', models.CharField(blank=True, max_length=100, null=True)),
                ('sk_document', models.FileField(blank=True, null=True, upload_to='docs/sk/%Y/%m/%d')),
                ('periode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='commite.Periode')),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='commite.CommitePosition')),
            ],
            options={
                'abstract': False,
            },
            bases=('member.basemember',),
        ),
    ]
